version = 1

exclude_patterns = ["**/node_modules/", "**/dist/", "**/build/", "**/target/", "**/pkg/", "**/.turbo/"]
test_patterns    = ["**/*.test.ts", "**/*.spec.ts"]

[[analyzers]]
meta = { environment = ["vitest", "nodejs", "browser"], plugins = ["react"] }
name = "javascript"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
meta = { msrv = "stable" }
name = "rust"

[[analyzers]]
name = "shell"

[[analyzers]]
meta = { dockerfile_paths = ["**/Dockerfile", "**/*.Dockerfile"] }
name = "docker"
