volumes:
  hash-qdrant:

services:
  hash-qdrant:
    image: qdrant/qdrant:v1.1.0
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - hash-qdrant:/qdrant/storage
    tmpfs:
      - /qdrant/snapshots
    ports:
      - "6333:6333"
