[tool.poetry]
name = "hash-agents"
version = "0.0.0"
description = ""
license = "GNU Affero General Public License v3.0"
authors = ["HASH"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.2.3"
langchain = "^0.0.137"
openai = "^0.27.4"
python-dotenv = "^1.0.0"
tiktoken = "^0.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
