blank_issues_enabled: true
contact_links:
  - name: Security Bug Bounty
    url: https://github.com/hashintel/hash/blob/main/.github/SECURITY.md
    about: Please see our security policy
  - name: X
    url: https://x.com/hashai
    about: Find us on X
  - name: Get in touch
    url: https://hash.ai/contact
    about: Reach out directly via our website
