[package]
name = "hash-type-fetcher"
version = "0.0.0"
edition = "2021"
authors = ["HASH"]
publish = false
description = "A RPC service to fetch external BP types"


[dependencies]
type-fetcher = { path = "../../lib/type-fetcher" }
graph = { path = "../../lib/graph", features = ["clap"] }
error-stack = { version = "0.3.0", features = ["spantrace"] }

# serde = { version = "1.0.152", features = ["derive"] }
# serde_json = "1.0.91"
futures = "0.3"
tokio = { version = "1.23.1", features = ["rt-multi-thread", "macros"] }
tarpc = { version = "0.31", features = ["serde1", "tokio1", "serde-transport", "tcp"] }
tokio-serde = { version = "0.8", features = ["messagepack"] }
clap = { version = "4.1.3", features = ["cargo", "derive", "env", "wrap_help"] }
clap_complete = "4.1.1"
tracing = "0.1.37"
