[package]
name = "hash-graph"
version = "0.0.0"
edition = "2021"
authors = ["HASH"]
publish = false
description = "The entity-graph query-layer for the HASH datastore"


[dependencies]
type-fetcher = { path = "../../lib/type-fetcher", optional = true }

axum = "0.6.7"
clap = { version = "4.1.6", features = ["cargo", "derive", "env", "wrap_help"] }
clap_complete = "4.1.2"
error-stack = { version = "0.3.1", features = ["spantrace"] }
futures = { version = "0.3.26", optional = true }
graph = { path = "../../lib/graph", features = ["clap"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
regex = "1.7.1"
serde_json = "1.0.93"
tarpc = { version = "0.31", features = ["serde1", "tokio1", "serde-transport", "tcp"], optional = true }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.7", default-features = false }
tokio-serde = { version = "0.8", features = ["messagepack"], optional = true }
tracing = "0.1.37"
type-system = { git = "https://github.com/blockprotocol/blockprotocol", rev = "2200c0f" }
uuid = "1.3.0"

# Remove again when the type fetcher is used in the graph
time = "0.3.19"

[features]
type-fetcher = ["dep:type-fetcher", "dep:tarpc", "dep:tokio-serde", "dep:futures", "graph/type-fetcher"]
