[package]
name = "hash-graph"
version = "0.0.0"
edition = "2021"
authors = ["HASH"]
publish = false
description = "The entity-graph query-layer for the HASH datastore"


[dependencies]
type-fetcher = { path = "../../lib/type-fetcher", optional = true }

axum = "0.6.18"
clap = { version = "4.2.7", features = ["cargo", "derive", "env", "wrap_help"] }
clap_complete = "4.2.3"
error-stack = { version = "0.3.1", features = ["spantrace"] }
futures = { version = "0.3.28" }
graph = { path = "../../lib/graph", features = ["clap"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
regex = "1.8.1"
semver = { version = "1.0.17", default-features = false }
serde_json = "1.0.96"
tarpc = { version = "0.33", features = ["serde1", "tokio1", "serde-transport", "tcp"], optional = true }
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.8", default-features = false }
tokio-serde = { version = "0.8", features = ["json"], optional = true }
tokio-util = { version = "0.7.8", default-features = false, features = ["codec"] }
tracing = "0.1.37"
type-system = { git = "https://github.com/blockprotocol/blockprotocol", rev = "cdde49" }
uuid = "1.3.3"

# Remove again when the type fetcher is used in the graph
time = "0.3.21"

[features]
test-server = ["graph/test-server"]
type-fetcher = ["dep:type-fetcher", "dep:tarpc", "dep:tokio-serde", "graph/type-fetcher"]
