[package]
name = "hash-graph"
version = "0.0.0"
edition = "2021"
authors = ["HASH"]
publish = false
description = "The entity-graph query-layer for the HASH datastore"


[dependencies]
graph = { path = "../../lib/graph", features = ["clap"] }
graph-types = { workspace = true }
type-fetcher = { path = "../../lib/type-fetcher" }
authorization = { workspace = true }
codec = { workspace = true }

error-stack = { workspace = true }
type-system = { workspace = true }

axum = "0.6.20"
clap = { version = "4.4.7", features = ["cargo", "derive", "env", "wrap_help"] }
clap_complete = "4.4.4"
futures = { version = "0.3.28" }
regex = "1.10.2"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
semver = { version = "1.0.20", default-features = false }
sentry = { version = "0.31.7", features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls"], default-features = false }
serde_json = "1.0.107"
tarpc = { version = "0.33", features = ["serde1", "tokio1", "serde-transport", "tcp"] }
time = "0.3.30"
tokio = { workspace = true }
tokio-postgres = { version = "0.7.10", default-features = false }
tokio-serde = { version = "0.8", features = ["json"] }
tokio-util = { workspace = true, features = ["codec"] }
tracing = "0.1.40"
uuid = "1.5.0"

[features]
test-server = ["graph/test-server"]
authorization = []
