[config]
default_to_workspace = false

[config.modify_core_tasks]
private = true
namespace = "default"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

CARGO_BUILD_FLAGS = "--workspace"

CARGO_RUN_FLAGS = ""

CARGO_FORMAT_FLAGS = ""
CARGO_FORMAT_HACK_FLAGS = "--workspace"

CARGO_CLIPPY_FLAGS = "--no-deps --all-targets"
CARGO_CLIPPY_HACK_FLAGS = "--workspace --feature-powerset"

CARGO_DOC_FLAGS = "--no-deps --all-features -Zunstable-options -Zrustdoc-scrape-examples"
CARGO_DOC_HACK_FLAGS = "--workspace"

CARGO_RUSTDOC_FLAGS = "--all-features -Zunstable-options -Zrustdoc-scrape-examples -- -Zunstable-options"
CARGO_RUSTDOC_HACK_FLAGS = "--workspace"

CARGO_TEST_FLAGS = ""
CARGO_TEST_HACK_FLAGS = "--workspace --feature-powerset"

CARGO_DOC_TEST_FLAGS = "--workspace --all-features"

CARGO_BENCH_FLAGS = ""
CARGO_BENCH_HACK_FLAGS = "--workspace"

CARGO_MIRI_FLAGS = "--all-targets"
CARGO_MIRI_HACK_FLAGS = "--workspace"

REPO_ROOT = { script = ["git rev-parse --show-toplevel"] }

[env.production]
CARGO_MAKE_CARGO_PROFILE = "release"

################################################################################
## General                                                                    ##
################################################################################

[tasks.default]
extend = "build"
category = ""

[tasks.all]
description = "Builds the project, checks lints, and runs the tests."
run_task = { name = ["build", "lint", "test"] }

[tasks.cargo]
private = true
command = "cargo"
dependencies = ["install-cargo-hack"]

[tasks.bash]
private = true
command = "bash"

[tasks.yarn]
command = "yarn"

[tasks.docker]
private = true
command = "docker"

################################################################################
## Build                                                                      ##
################################################################################

[tasks.build]
category = "Build"
description = "Builds the crate"
run_task = { name = "build-task" }

[tasks.build-task]
extend = "cargo"
args = ["build", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_BUILD_FLAGS, )", "${@}"]

################################################################################
## Run                                                                        ##
################################################################################

[tasks.run]
category = "Run"
description = "Builds the binary and runs it"
run_task = { name = "run-task" }

[tasks.run-task]
extend = "cargo"
args = ["run", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_RUN_FLAGS, )", "${@}"]

################################################################################
## Lints                                                                      ##
################################################################################

[tasks.lint]
category = "Lint"
description = "Runs all lints"
run_task = { name = ["format", "clippy", "doc"] }

[tasks.format]
category = "Lint"
description = "Runs the rustfmt formatter"
run_task = { name = ["format-task"] }

[tasks.format-task]
extend = "cargo"
args = ["hack", "@@split(CARGO_FORMAT_HACK_FLAGS, )", "fmt", "@@split(CARGO_FORMAT_FLAGS, )", "${@}"]
dependencies = ["install-rustfmt"]

[tasks.clippy]
category = "Lint"
description = "Runs clippy with all feature flag permutations"
run_task = { name = ["clippy-task"] }

[tasks.clippy-task]
extend = "cargo"
args = ["hack", "@@split(CARGO_CLIPPY_HACK_FLAGS, )", "clippy", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_CLIPPY_FLAGS, )", "${@}"]
dependencies = ["install-clippy"]

################################################################################
## Docs                                                                       ##
################################################################################

[tasks.doc]
category = "Docs"
description = "Builds the documentation for the crate"
run_task = { name = ["doc-task"] }

[tasks.doc-task]
extend = "cargo"
args = ["hack", "@@split(CARGO_DOC_HACK_FLAGS, )", "doc", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_DOC_FLAGS, )", "${@}"]

[tasks.rustdoc]
category = "Docs"
description = "Builds the documentation for the crate"
run_task = { name = ["rustdoc-task"] }

[tasks.rustdoc-task]
extend = "cargo"
args = ["hack", "@@split(CARGO_RUSTDOC_HACK_FLAGS, )", "rustdoc", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_RUSTDOC_FLAGS, )", "${@}"]

################################################################################
## Tests                                                                      ##
################################################################################

[tasks.test]
category = "Test"
description = "Runs the test suite"
run_task = { name = ["test-task"] }

[tasks.test-task]
private = true
run_task = { name = ["test-task-lib", "test-task-doc"]}

[tasks.test-task-lib]
extend = "cargo"
args = ["hack", "@@split(CARGO_TEST_HACK_FLAGS, )", "nextest", "run", "--cargo-profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_TEST_FLAGS, )", "${@}"]
dependencies = ["install-cargo-nextest"]

[tasks.test-task-doc]
extend = "cargo"
args = ["test", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_DOC_TEST_FLAGS, )", "--doc", "${@}"]

[tasks.coverage]
category = "Test"
description = "Runs the coverage suite"
run_task = { name = ["coverage-task"] }

[tasks.coverage-task]
extend = "cargo"
args = ["llvm-cov", "nextest", "--workspace", "--all-features", "--all-targets", "${@}"]
dependencies = ["install-llvm-tools", "install-cargo-nextest"]

[tasks.miri]
category = "Test"
description = "Runs miri tests suite"
run_task = { name = ["miri-task-no-features", "miri-task", "miri-task-all-features"] }

[tasks.miri-task-no-features]
extend = "cargo"
args = ["hack", "@@split(CARGO_MIRI_HACK_FLAGS, )", "miri", "test", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_MIRI_FLAGS, )", "--no-default-features", "${@}"]
dependencies = ["install-miri"]

[tasks.miri-task]
extend = "cargo"
args = ["hack", "@@split(CARGO_MIRI_HACK_FLAGS, )", "miri", "test", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_MIRI_FLAGS, )", "${@}"]
dependencies = ["install-miri"]

[tasks.miri-task-all-features]
extend = "cargo"
args = ["hack", "@@split(CARGO_MIRI_HACK_FLAGS, )", "miri", "test", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_MIRI_FLAGS, )", "--all-features", "${@}"]
dependencies = ["install-miri"]

################################################################################
## Bench                                                                      ##
################################################################################

[tasks.bench]
category = "Bench"
description = "Runs the benchmark suite"
run_task = { name = ["bench-task"] }

[tasks.bench-task]
extend = "cargo"
args = ["hack", "@@split(CARGO_BENCH_HACK_FLAGS, )", "bench", "@@split(CARGO_BENCH_FLAGS, )", "${@}"]

################################################################################
## Tool Installs                                                              ##
################################################################################

[tasks.install-clippy]
private = true
install_crate = { rustup_component_name = "clippy" }

[tasks.install-rustfmt]
private = true
install_crate = { rustup_component_name = "rustfmt" }

[tasks.install-llvm-tools]
private = true
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.install-miri]
private = true
condition = { channels = ["nightly"] }
install_crate = { rustup_component_name = "miri" }

[tasks.install-cargo-hack]
private = true
install_crate = { crate_name = "cargo-hack", version = "0.5.26", binary = "cargo", test_arg = ["hack", "--version"] }

[tasks.install-cargo-nextest]
private = true
install_crate = { crate_name = "cargo-nextest", version = "0.9.28", binary = "cargo", test_arg = ["nextest", "--version"] }
