[config]
default_to_workspace = false

[config.modify_core_tasks]
private = true
namespace = "default"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_BUILD_FLAGS = ""
CARGO_BUILD_HACK_FLAGS = "--workspace"
CARGO_RUN_FLAGS = ""
CARGO_RUN_HACK_FLAGS = ""
CARGO_FORMAT_FLAGS = ""
CARGO_FORMAT_HACK_FLAGS = "--workspace"
CARGO_CLIPPY_FLAGS = "--no-deps --tests"
CARGO_CLIPPY_HACK_FLAGS = "--workspace --feature-powerset"
CARGO_DOC_FLAGS = "--no-deps --all-features -Zunstable-options -Zrustdoc-scrape-examples=examples"
CARGO_DOC_HACK_FLAGS = "--workspace"
CARGO_RUSTDOC_FLAGS = "--all-features -Zunstable-options -Zrustdoc-scrape-examples=examples"
CARGO_RUSTDOC_HACK_FLAGS = "--workspace"
CARGO_TEST_FLAGS = ""
CARGO_TEST_HACK_FLAGS = "--workspace --feature-powerset"
CARGO_MIRI_FLAGS = ""
CARGO_MIRI_HACK_FLAGS = "--workspace --feature-powerset"

[env.production]
CARGO_MAKE_CARGO_PROFILE = "release"


[tasks.default]
extend = "build"
category = ""

[tasks.everything]
description = "Builds the project, checks lints, and runs the tests."
run_task = { name = ["build", "format", "clippy", "doc", "rustdoc", "test", "miri"] }

[tasks.all]
description = "Builds the project, checks lints, and runs the tests."
run_task = { name = ["build", "lint", "test"] }


[tasks.task]
private = true
command = "cargo"

################################################################################
## Build                                                                      ##
################################################################################
[tasks.build]
category = "Build"
description = "Builds the crate"
run_task = { name = "build-task" }

[tasks.build-task]
extend = "task"
args = ["hack", "@@split(CARGO_BUILD_HACK_FLAGS, )", "build", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_BUILD_FLAGS, )", "${@}"]


################################################################################
## Run                                                                        ##
################################################################################
[tasks.run]
category = "Run"
description = "Builds the binary and runs it"
run_task = { name = "run-task" }

[tasks.run-task]
extend = "task"
args = ["hack", "@@split(CARGO_RUN_HACK_FLAGS, )", "run", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_RUN_FLAGS, )", "${@}"]


################################################################################
## Lints                                                                      ##
################################################################################
[tasks.lint]
category = "Lint"
description = "Runs all lints"
run_task = { name = ["format", "clippy", "doc"] }


[tasks.format]
category = "Lint"
description = "Runs the rustfmt formatter"
run_task = { name = ["format-task"] }

[tasks.format-task]
extend = "task"
args = ["hack", "@@split(CARGO_FORMAT_HACK_FLAGS, )", "fmt", "@@split(CARGO_FORMAT_FLAGS, )", "${@}"]
dependencies = ["install-rustfmt"]


[tasks.clippy]
description = "Runs clippy with all feature flag permutations"
category = "Lint"
run_task = { name = ["clippy-task"] }

[tasks.clippy-task]
extend = "task"
args = ["hack", "@@split(CARGO_CLIPPY_HACK_FLAGS, )", "clippy", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_CLIPPY_FLAGS, )", "${@}"]
dependencies = ["install-clippy"]


################################################################################
## Docs                                                                       ##
################################################################################
[tasks.doc]
category = "Docs"
description = "Builds the documentation for the crate"
run_task = { name = ["doc-task"] }

[tasks.doc-task]
extend = "task"
args = ["hack", "@@split(CARGO_DOC_HACK_FLAGS, )", "doc", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_DOC_FLAGS, )", "${@}"]


[tasks.rustdoc]
category = "Docs"
description = "Builds the documentation for the crate"
run_task = { name = ["rustdoc-task"] }

[tasks.rustdoc-task]
extend = "task"
args = ["hack", "@@split(CARGO_RUSTDOC_HACK_FLAGS, )", "rustdoc", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_RUSTDOC_FLAGS, )", "${@}"]


################################################################################
## Tests                                                                      ##
################################################################################
[tasks.test]
category = "Test"
description = "Runs the test suite"
run_task = { name = ["test-task"] }

[tasks.test-task]
extend = "task"
args = ["hack", "@@split(CARGO_TEST_HACK_FLAGS, )", "test", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_TEST_FLAGS, )", "${@}"]


[tasks.miri]
category = "Test"
description = "Runs miri tests suite"
run_task = { name = ["miri-task"] }

[tasks.miri-task]
extend = "task"
args = ["hack", "@@split(CARGO_MIRI_HACK_FLAGS, )", "miri", "test", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "@@split(CARGO_MIRI_FLAGS, )", "${@}"]
dependencies = ["install-miri"]


################################################################################
## Tools                                                                      ##
################################################################################
[tasks.install-clippy]
private = true
install_crate = { rustup_component_name = "clippy" }

[tasks.install-rustfmt]
private = true
install_crate = { rustup_component_name = "rustfmt" }

[tasks.install-miri]
private = true
condition = { channels = ["nightly"] }
install_crate = { rustup_component_name = "miri" }
