[package]
name = "hash_engine"
version = "0.0.0"
edition = "2021"

[dependencies]
hash_engine_lib = { path = "../..", default-features = false }
error-stack = { path = "../../../libs/error-stack", features = ["spantrace"] }

tokio = "1.18.2"
tracing = "0.1.29"

[[bin]]
name = "hash_engine"
path = "src/main.rs"

[features]
default = ["build-nng"]
texray = ["hash_engine_lib/texray"]
build-nng = ["hash_engine_lib/build-nng"]
