[package]
name = "hash_engine"
version = "0.0.0"
edition = "2021"

[dependencies]
execution = { path = "../../lib/execution", default-features = false }
experiment-structure = { path = "../../lib/experiment-structure", default-features = false }
experiment-control = { path = "../../lib/experiment-control", default-features = false, features = ["clap"] }

error-stack = { version = "0.1.1", features = ["spantrace"] }

tokio = "1.18.2"
tracing = "0.1.29"

[[bin]]
name = "hash_engine"
path = "src/main.rs"

[features]
default = ["build-nng"]
texray = ["experiment-control/texray"]
build-nng = ["experiment-control/build-nng"]