name: MDX Lint

on:
  push:
    branches: [ main, aj/md-lint ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Lint for markdown correctness
        run: npm i && npm run lint:markdownlint

      # Runs a single command using the runners shell
      - name: Lint for objectID
        run: cd .github/workflows/algolia && sh objectid_lint.sh
